# Data Understanding

| # | اسم العمود | نوع البيانات | الشرح |
|---|---|---|---|
| 1 | `order_id` | ID | رقم مميز لكل طلب |
| 2 | `customer_id` | ID | رقم مميز لكل عميل |
| 3 | `restaurant_id` | ID | رقم مميز لكل مطعم |
| 4 | `driver_id` | ID | رقم مميز لكل سائق توصيل |
| 5 | `order_timestamp` | DateTime | تاريخ ووقت إنشاء الطلب |
| 6 | `order_date` | Date | تاريخ إنشاء الطلب |
| 7 | `order_hour` | رقمي | ساعة إنشاء الطلب خلال اليوم |
| 8 | `day_of_week` | فئوي | يوم الأسبوع الذي تم فيه إنشاء الطلب |
| 9 | `is_weekend` | ثنائي | يحدد هل الطلب في عطلة نهاية الأسبوع أم لا |
| 10 | `city` | فئوي | المدينة التي تم فيها الطلب أو التوصيل |
| 11 | `delivery_area` | فئوي | منطقة توصيل الطلب |
| 12 | `customer_age` | رقمي | عمر العميل |
| 13 | `customer_type` | فئوي | نوع أو فئة العميل |
| 14 | `restaurant_type` | فئوي | نوع المطعم |
| 15 | `restaurant_primary_category` | فئوي | التصنيف الأساسي أو نوع الطعام في المطعم |
| 16 | `restaurant_rating` | رقمي | تقييم العميل للمطعم |
| 17 | `items_count` | رقمي | عدد الأصناف الموجودة في الطلب |
| 18 | `subtotal` | رقمي | قيمة المنتجات قبل الضرائب والرسوم والخصومات |
| 19 | `discount_percent` | رقمي | نسبة الخصم المطبقة على الطلب |
| 20 | `tax_amount` | رقمي | قيمة الضريبة على الطلب |
| 21 | `service_fee` | رقمي | رسوم الخدمة |
| 22 | `delivery_fee` | رقمي | رسوم توصيل الطلب |
| 23 | `order_total` | رقمي | إجمالي قيمة الطلب بعد إضافة الرسوم والضرائب والخصومات |
| 24 | `payment_method` | فئوي | طريقة الدفع المستخدمة في الطلب |
| 25 | `tip_amount` | رقمي | قيمة البقشيش الذي حصل عليه السائق |
| 26 | `distance_km` | رقمي | المسافة بين المطعم ومكان التوصيل بالكيلومتر |
| 27 | `weather` | فئوي | حالة الطقس أثناء عملية التوصيل |
| 28 | `traffic_level` | فئوي | مستوى الزحام أثناء عملية التوصيل |
| 29 | `delivery_partner_experience_months` | رقمي | خبرة السائق في التوصيل بعدد الشهور |
| 30 | `delivery_partner_rating` | رقمي | تقييم السائق |
| 31 | `restaurant_preparation_time_minutes` | رقمي | الوقت الذي استغرقه المطعم في تجهيز الطلب بالدقائق |
| 32 | `estimated_delivery_time_minutes` | رقمي | الوقت المتوقع لتوصيل الطلب بالدقائق |
| 33 | `actual_delivery_time_minutes` | رقمي | الوقت الفعلي الذي استغرقه توصيل الطلب بالدقائق |
| 34 | `late_delivery` | ثنائي | يحدد هل تم توصيل الطلب متأخرًا أم لا |
| 35 | `order_status` | فئوي | الحالة النهائية للطلب مثل مكتمل أو ملغي |
| 36 | `cancellation_reason` | فئوي | سبب إلغاء الطلب في حالة إلغائه |
| 37 | `customer_rating` | رقمي | تقييم العميل لتجربة التوصيل |

In [5]:
import numpy as np
import pandas as pd
import plotly.express as px

In [6]:
df = pd.read_csv('food_delivery_orders_dataset.csv')
df

,order_id,customer_id,restaurant_id,driver_id,order_timestamp,order_date,order_hour,day_of_week,is_weekend,city,...,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes,late_delivery,order_status,cancellation_reason,customer_rating
0,ORD_000001,CUS_00001,RES_0008,DRV_0075,2025-10-05 15:54:00,2025-10-05,15,Sunday,1,City_C,...,Medium,14,4.4,25,25,29.0,0.0,Completed,NaN,4.6
1,ORD_000002,CUS_00013,RES_0024,DRV_0131,2025-10-01 20:00:00,2025-10-01,20,Wednesday,0,City_A,...,High,44,4.7,12,20,24.0,0.0,Completed,NaN,5.0
2,ORD_000003,CUS_00049,RES_0013,DRV_0087,2025-10-07 18:24:00,2025-10-07,18,Tuesday,0,City_C,...,High,1,5.0,11,63,72.0,1.0,Completed,NaN,3.6
3,ORD_000004,CUS_00007,RES_0001,DRV_0177,2025-10-30 16:54:00,2025-10-30,16,Thursday,0,City_A,...,Low,50,4.3,12,23,31.0,1.0,Completed,NaN,4.1
4,ORD_000005,CUS_00325,RES_0029,DRV_0114,2025-10-15 18:34:00,2025-10-15,18,Wednesday,0,City_B,...,Medium,21,4.0,9,32,42.0,1.0,Completed,NaN,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD_049996,CUS_00280,RES_0130,DRV_0112,2025-10-25 12:16:00,2025-10-25,12,Saturday,1,City_B,...,Medium,34,5.0,11,19,21.0,0.0,Completed,NaN,4.4
49996,ORD_049997,CUS_00893,RES_0028,DRV_0036,2025-10-05 19:48:00,2025-10-05,19,Sunday,1,City_B,...,High,49,5.0,9,28,29.0,0.0,Completed,NaN,4.8
49997,ORD_049998,CUS_01618,RES_0001,DRV_0071,2025-10-08 12:18:00,2025-10-08,12,Wednesday,0,City_A,...,High,54,4.1,11,18,16.0,0.0,Completed,NaN,4.7
49998,ORD_049999,CUS_00025,RES_0057,DRV_0103,2025-10-20 17:39:00,2025-10-20,17,Monday,0,City_A,...,High,33,4.0,20,17,27.0,1.0,Completed,NaN,3.8
49999,ORD_050000,CUS_00038,RES_0139,DRV_0131,2025-10-13 17:36:00,2025-10-13,17,Monday,0,City_A,...,Low,44,4.7,12,30,40.0,1.0,Completed,NaN,4.5

# Data Exploration

In [7]:
# Check Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 37 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   order_id                             50000 non-null  object
 1   customer_id                          50000 non-null  object
 2   restaurant_id                        50000 non-null  object
 3   driver_id                            50000 non-null  object
 4   order_timestamp                      50000 non-null  object
 5   order_date                           50000 non-null  object
 6   order_hour                           50000 non-null  int64
 7   day_of_week                          50000 non-null  object
 8   is_weekend                           50000 non-null  int64
 9   city                                 50000 non-null  object
 10  delivery_area                        50000 non-null  object
 11  customer_age                         50000 non-null  int64
 12  customer_type                        50000 non-null  object
 13  restaurant_type                      50000 non-null  object
 14  restaurant_primary_category          50000 non-null  object
 15  restaurant_rating                    50000 non-null  float64
 16  items_count                          50000 non-null  int64
 17  subtotal                             50000 non-null  float64
 18  discount_percent                     50000 non-null  int64
 19  tax_amount                           50000 non-null  float64
 20  service_fee                          50000 non-null  float64
 21  delivery_fee                         50000 non-null  float64
 22  order_total                          50000 non-null  float64
 23  payment_method                       50000 non-null  object
 24  tip_amount                           49132 non-null  float64
 25  distance_km                          50000 non-null  float64
 26  weather                              50000 non-null  object
 27  traffic_level                        50000 non-null  object
 28  delivery_partner_experience_months   50000 non-null  int64
 29  delivery_partner_rating              50000 non-null  float64
 30  restaurant_preparation_time_minutes  50000 non-null  int64
 31  estimated_delivery_time_minutes      50000 non-null  int64
 32  actual_delivery_time_minutes         49132 non-null  float64
 33  late_delivery                        49132 non-null  float64
 34  order_status                         50000 non-null  object
 35  cancellation_reason                  868 non-null    object
 36  customer_rating                      49132 non-null  float64
dtypes: float64(12), int64(8), object(17)
memory usage: 14.1+ MB

In [8]:
# Convert columns to lowercase
df.columns = df.columns.str.lower()
df.columns

Index(['order_id', 'customer_id', 'restaurant_id', 'driver_id',
       'order_timestamp', 'order_date', 'order_hour', 'day_of_week',
       'is_weekend', 'city', 'delivery_area', 'customer_age', 'customer_type',
       'restaurant_type', 'restaurant_primary_category', 'restaurant_rating',
       'items_count', 'subtotal', 'discount_percent', 'tax_amount',
       'service_fee', 'delivery_fee', 'order_total', 'payment_method',
       'tip_amount', 'distance_km', 'weather', 'traffic_level',
       'delivery_partner_experience_months', 'delivery_partner_rating',
       'restaurant_preparation_time_minutes',
       'estimated_delivery_time_minutes', 'actual_delivery_time_minutes',
       'late_delivery', 'order_status', 'cancellation_reason',
       'customer_rating'],
      dtype='object')

In [9]:
# Check summary statistics for numerical columns
df.describe().round()

,order_hour,is_weekend,customer_age,restaurant_rating,items_count,subtotal,discount_percent,tax_amount,service_fee,delivery_fee,order_total,tip_amount,distance_km,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes,late_delivery,customer_rating
count,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,49132.0,50000.0,50000.0,50000.0,50000.0,50000.0,49132.0,49132.0,49132.0
mean,14.0,0.0,28.0,4.0,3.0,31.0,4.0,4.0,1.0,3.0,38.0,2.0,5.0,30.0,4.0,16.0,31.0,35.0,0.0,4.0
std,5.0,0.0,8.0,0.0,2.0,27.0,6.0,4.0,1.0,2.0,31.0,3.0,3.0,17.0,0.0,7.0,13.0,15.0,0.0,1.0
min,0.0,0.0,18.0,3.0,1.0,5.0,0.0,1.0,0.0,0.0,5.0,0.0,1.0,1.0,3.0,5.0,8.0,10.0,0.0,2.0
25%,11.0,0.0,21.0,4.0,1.0,13.0,0.0,2.0,1.0,0.0,17.0,0.0,3.0,14.0,4.0,10.0,22.0,25.0,0.0,4.0
50%,14.0,0.0,27.0,4.0,2.0,23.0,0.0,3.0,1.0,4.0,28.0,0.0,4.0,29.0,4.0,14.0,28.0,33.0,0.0,4.0
75%,19.0,1.0,33.0,5.0,4.0,40.0,10.0,5.0,2.0,4.0,49.0,2.0,6.0,44.0,5.0,19.0,37.0,42.0,1.0,5.0
max,23.0,1.0,55.0,5.0,10.0,363.0,20.0,51.0,25.0,12.0,443.0,54.0,20.0,60.0,5.0,73.0,128.0,172.0,1.0,5.0

In [10]:
# Check summary statistics for categorical columns
df.describe(include= ['object'])

,order_id,customer_id,restaurant_id,driver_id,order_timestamp,order_date,day_of_week,city,delivery_area,customer_type,restaurant_type,restaurant_primary_category,payment_method,weather,traffic_level,order_status,cancellation_reason
count,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,868
unique,50000,4979,250,200,25459,30,7,4,40,3,4,6,3,4,3,2,5
top,ORD_000001,CUS_00001,RES_0001,DRV_0066,2025-10-02 19:17:00,2025-10-23,Thursday,City_A,City_A_Area_1,Regular,Fast Food,Burger,Credit Card,Clear,Medium,Completed,Driver Unassigned
freq,1,4510,8837,315,9,1741,8472,19888,2056,25098,27593,16184,24971,28248,19522,49132,386

In [11]:
# Check duplicates
df.duplicated().sum()

np.int64(0)

In [12]:
df

,order_id,customer_id,restaurant_id,driver_id,order_timestamp,order_date,order_hour,day_of_week,is_weekend,city,...,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes,late_delivery,order_status,cancellation_reason,customer_rating
0,ORD_000001,CUS_00001,RES_0008,DRV_0075,2025-10-05 15:54:00,2025-10-05,15,Sunday,1,City_C,...,Medium,14,4.4,25,25,29.0,0.0,Completed,NaN,4.6
1,ORD_000002,CUS_00013,RES_0024,DRV_0131,2025-10-01 20:00:00,2025-10-01,20,Wednesday,0,City_A,...,High,44,4.7,12,20,24.0,0.0,Completed,NaN,5.0
2,ORD_000003,CUS_00049,RES_0013,DRV_0087,2025-10-07 18:24:00,2025-10-07,18,Tuesday,0,City_C,...,High,1,5.0,11,63,72.0,1.0,Completed,NaN,3.6
3,ORD_000004,CUS_00007,RES_0001,DRV_0177,2025-10-30 16:54:00,2025-10-30,16,Thursday,0,City_A,...,Low,50,4.3,12,23,31.0,1.0,Completed,NaN,4.1
4,ORD_000005,CUS_00325,RES_0029,DRV_0114,2025-10-15 18:34:00,2025-10-15,18,Wednesday,0,City_B,...,Medium,21,4.0,9,32,42.0,1.0,Completed,NaN,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD_049996,CUS_00280,RES_0130,DRV_0112,2025-10-25 12:16:00,2025-10-25,12,Saturday,1,City_B,...,Medium,34,5.0,11,19,21.0,0.0,Completed,NaN,4.4
49996,ORD_049997,CUS_00893,RES_0028,DRV_0036,2025-10-05 19:48:00,2025-10-05,19,Sunday,1,City_B,...,High,49,5.0,9,28,29.0,0.0,Completed,NaN,4.8
49997,ORD_049998,CUS_01618,RES_0001,DRV_0071,2025-10-08 12:18:00,2025-10-08,12,Wednesday,0,City_A,...,High,54,4.1,11,18,16.0,0.0,Completed,NaN,4.7
49998,ORD_049999,CUS_00025,RES_0057,DRV_0103,2025-10-20 17:39:00,2025-10-20,17,Monday,0,City_A,...,High,33,4.0,20,17,27.0,1.0,Completed,NaN,3.8
49999,ORD_050000,CUS_00038,RES_0139,DRV_0131,2025-10-13 17:36:00,2025-10-13,17,Monday,0,City_A,...,Low,44,4.7,12,30,40.0,1.0,Completed,NaN,4.5

In [13]:
# Check Missing Values
df.isna().sum()

order_id                                   0
customer_id                                0
restaurant_id                              0
driver_id                                  0
order_timestamp                            0
order_date                                 0
order_hour                                 0
day_of_week                                0
is_weekend                                 0
city                                       0
delivery_area                              0
customer_age                               0
customer_type                              0
restaurant_type                            0
restaurant_primary_category                0
restaurant_rating                          0
items_count                                0
subtotal                                   0
discount_percent                           0
tax_amount                                 0
service_fee                                0
delivery_fee                               0
order_total                                0
payment_method                             0
tip_amount                               868
distance_km                                0
weather                                    0
traffic_level                              0
delivery_partner_experience_months         0
delivery_partner_rating                    0
restaurant_preparation_time_minutes        0
estimated_delivery_time_minutes            0
actual_delivery_time_minutes             868
late_delivery                            868
order_status                               0
cancellation_reason                    49132
customer_rating                          868
dtype: int64

In [14]:
# Check Missing Values Percentage
df.isna().mean().round(4) * 100

order_id                                0.00
customer_id                             0.00
restaurant_id                           0.00
driver_id                               0.00
order_timestamp                         0.00
order_date                              0.00
order_hour                              0.00
day_of_week                             0.00
is_weekend                              0.00
city                                    0.00
delivery_area                           0.00
customer_age                            0.00
customer_type                           0.00
restaurant_type                         0.00
restaurant_primary_category             0.00
restaurant_rating                       0.00
items_count                             0.00
subtotal                                0.00
discount_percent                        0.00
tax_amount                              0.00
service_fee                             0.00
delivery_fee                            0.00
order_total                             0.00
payment_method                          0.00
tip_amount                              1.74
distance_km                             0.00
weather                                 0.00
traffic_level                           0.00
delivery_partner_experience_months      0.00
delivery_partner_rating                 0.00
restaurant_preparation_time_minutes     0.00
estimated_delivery_time_minutes         0.00
actual_delivery_time_minutes            1.74
late_delivery                           1.74
order_status                            0.00
cancellation_reason                    98.26
customer_rating                         1.74
dtype: float64

In [15]:
(df.dropna().shape[0] / df.shape[0]) * 100

0.0

In [16]:
# Check order_status values
df['order_status'].value_counts()

order_status
Completed    49132
Cancelled      868
Name: count, dtype: int64

In [17]:
# Check cancellation_reason values
df['cancellation_reason'].value_counts()

cancellation_reason
Driver Unassigned         386
Restaurant Unavailable    160
Customer Cancelled        154
Changed Mind              153
Long Prep Delay            15
Name: count, dtype: int64

# Data Cleaning

In [18]:
df.dropna(subset=['actual_delivery_time_minutes'], inplace= True)

In [19]:
df.reset_index(inplace= True, drop= True)

In [20]:
# Check Missing Values after dropping cancelled orders
df.isna().sum()

order_id                                   0
customer_id                                0
restaurant_id                              0
driver_id                                  0
order_timestamp                            0
order_date                                 0
order_hour                                 0
day_of_week                                0
is_weekend                                 0
city                                       0
delivery_area                              0
customer_age                               0
customer_type                              0
restaurant_type                            0
restaurant_primary_category                0
restaurant_rating                          0
items_count                                0
subtotal                                   0
discount_percent                           0
tax_amount                                 0
service_fee                                0
delivery_fee                               0
order_total                                0
payment_method                             0
tip_amount                                 0
distance_km                                0
weather                                    0
traffic_level                              0
delivery_partner_experience_months         0
delivery_partner_rating                    0
restaurant_preparation_time_minutes        0
estimated_delivery_time_minutes            0
actual_delivery_time_minutes               0
late_delivery                              0
order_status                               0
cancellation_reason                    49132
customer_rating                            0
dtype: int64

In [21]:
df.drop(['order_id', 'customer_id', 'restaurant_id', 'driver_id',"discount_percent",
         'order_timestamp', 'order_date', 'order_status', 'cancellation_reason',
         'late_delivery', 'tip_amount', 'customer_rating',"customer_age",
          'payment_method', 'customer_type',
         'subtotal', 'tax_amount', 'service_fee', 'delivery_fee',
         'order_total'],
        axis= 1, inplace= True)

In [22]:
# Check duplicates after dropping columns
df.duplicated().sum()

np.int64(0)

In [23]:
df.head()

,order_hour,day_of_week,is_weekend,city,delivery_area,restaurant_type,restaurant_primary_category,restaurant_rating,items_count,distance_km,weather,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes
0,15,Sunday,1,City_C,City_C_Area_3,Casual Dining,Healthy,4.4,4,1.1,Rain,Medium,14,4.4,25,25,29.0
1,20,Wednesday,0,City_A,City_A_Area_1,Cafe,Dessert,4.4,2,2.5,Cloudy,High,44,4.7,12,20,24.0
2,18,Tuesday,0,City_C,City_C_Area_3,Fast Food,Dessert,4.8,1,11.8,Cloudy,High,1,5.0,11,63,72.0
3,16,Thursday,0,City_A,City_A_Area_1,Fast Food,Local,3.9,1,5.4,Cloudy,Low,50,4.3,12,23,31.0
4,18,Wednesday,0,City_B,City_B_Area_6,Casual Dining,Pizza,3.5,1,6.1,Rain,Medium,21,4.0,9,32,42.0

- In depth check for Numerical columns

In [24]:
num_cols = df.select_dtypes(include= 'number').columns.drop('actual_delivery_time_minutes')
num_cols

Index(['order_hour', 'is_weekend', 'restaurant_rating', 'items_count',
       'distance_km', 'delivery_partner_experience_months',
       'delivery_partner_rating', 'restaurant_preparation_time_minutes',
       'estimated_delivery_time_minutes'],
      dtype='object')

In [25]:
for col in num_cols:
    px.histogram(data_frame= df, x= col, title= col).show()
    px.box(data_frame= df, x= col, title= col).show()

- In depth check for categorical columns

In [26]:
cat_cols = df.select_dtypes(include= 'object').columns
cat_cols

Index(['day_of_week', 'city', 'delivery_area', 'restaurant_type',
       'restaurant_primary_category', 'weather', 'traffic_level'],
      dtype='object')

In [27]:
for col in cat_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 50)

day_of_week
7
['Sunday' 'Wednesday' 'Tuesday' 'Thursday' 'Friday' 'Monday' 'Saturday']
--------------------------------------------------
city
4
['City_C' 'City_A' 'City_B' 'City_D']
--------------------------------------------------
delivery_area
40
['City_C_Area_3' 'City_A_Area_1' 'City_B_Area_6' 'City_D_Area_10'
 'City_C_Area_4' 'City_B_Area_9' 'City_A_Area_8' 'City_C_Area_8'
 'City_A_Area_6' 'City_A_Area_10' 'City_A_Area_3' 'City_B_Area_5'
 'City_D_Area_1' 'City_B_Area_8' 'City_B_Area_3' 'City_C_Area_9'
 'City_B_Area_10' 'City_A_Area_7' 'City_D_Area_6' 'City_A_Area_2'
 'City_A_Area_5' 'City_C_Area_10' 'City_A_Area_9' 'City_C_Area_7'
 'City_B_Area_4' 'City_C_Area_1' 'City_B_Area_1' 'City_D_Area_8'
 'City_A_Area_4' 'City_B_Area_7' 'City_B_Area_2' 'City_D_Area_9'
 'City_C_Area_5' 'City_D_Area_5' 'City_C_Area_6' 'City_D_Area_2'
 'City_C_Area_2' 'City_D_Area_7' 'City_D_Area_3' 'City_D_Area_4']
--------------------------------------------------
restaurant_type
4
['Casual Dining' 'Cafe' 'Fast Food' 'Fine Dining']
--------------------------------------------------
restaurant_primary_category
6
['Healthy' 'Dessert' 'Local' 'Pizza' 'Burger' 'Asian']
--------------------------------------------------
weather
4
['Rain' 'Cloudy' 'Clear' 'Storm']
--------------------------------------------------
traffic_level
3
['Medium' 'High' 'Low']
--------------------------------------------------

In [28]:
px.histogram(data_frame= df, x= 'actual_delivery_time_minutes')

In [29]:
px.scatter(
    df,
    x="items_count",
    y="actual_delivery_time_minutes",
    trendline="ols"
)

In [30]:
df.head()

,order_hour,day_of_week,is_weekend,city,delivery_area,restaurant_type,restaurant_primary_category,restaurant_rating,items_count,distance_km,weather,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes
0,15,Sunday,1,City_C,City_C_Area_3,Casual Dining,Healthy,4.4,4,1.1,Rain,Medium,14,4.4,25,25,29.0
1,20,Wednesday,0,City_A,City_A_Area_1,Cafe,Dessert,4.4,2,2.5,Cloudy,High,44,4.7,12,20,24.0
2,18,Tuesday,0,City_C,City_C_Area_3,Fast Food,Dessert,4.8,1,11.8,Cloudy,High,1,5.0,11,63,72.0
3,16,Thursday,0,City_A,City_A_Area_1,Fast Food,Local,3.9,1,5.4,Cloudy,Low,50,4.3,12,23,31.0
4,18,Wednesday,0,City_B,City_B_Area_6,Casual Dining,Pizza,3.5,1,6.1,Rain,Medium,21,4.0,9,32,42.0

# Data Preprocessing for ML

- 1) Split Data into Input & Output Features

In [31]:
x = df.drop('actual_delivery_time_minutes', axis= 1)
y = df['actual_delivery_time_minutes']

### Numerical Pipeline

In [32]:
num_cols = x.select_dtypes(include= 'number').columns
num_cols

Index(['order_hour', 'is_weekend', 'restaurant_rating', 'items_count',
       'distance_km', 'delivery_partner_experience_months',
       'delivery_partner_rating', 'restaurant_preparation_time_minutes',
       'estimated_delivery_time_minutes'],
      dtype='object')

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler

median_impute = SimpleImputer(strategy= 'median')
rc = RobustScaler()

num_pipeline = Pipeline(steps= [('Median Impute', median_impute),
                                ('Scaling', rc)])
num_pipeline

Pipeline(steps=[('Median Impute', SimpleImputer(strategy='median')),
                ('Scaling', RobustScaler())])

### Categorical Pipeline

- BE Pipeline

In [34]:
BE_cols = ['delivery_area']
BE_cols

['delivery_area']

In [35]:
from category_encoders import BinaryEncoder

const_imputer = SimpleImputer(strategy= 'constant', fill_value= 'Other')
BE = BinaryEncoder()

BE_pipeline = Pipeline(steps= [('Const Impute', const_imputer),
                               ('Binary Encoder', BE)  ])
BE_pipeline

Pipeline(steps=[('Const Impute',
                 SimpleImputer(fill_value='Other', strategy='constant')),
                ('Binary Encoder', BinaryEncoder())])

- Ordinal Pipeline

In [36]:
ord_cols = ['traffic_level', 'weather']
ord_cols

['traffic_level', 'weather']

In [37]:
from sklearn.preprocessing import OrdinalEncoder

ord = OrdinalEncoder(categories= [
                                   ['Low', 'Medium', 'High'],
                                   ['Clear', 'Cloudy', 'Rain', 'Storm'] ])

ord_pipeline = Pipeline(steps= [ ('Ordinal Encoder', ord) ])
ord_pipeline

Pipeline(steps=[('Ordinal Encoder',
                 OrdinalEncoder(categories=[['Low', 'Medium', 'High'],
                                            ['Clear', 'Cloudy', 'Rain',
                                             'Storm']]))])

- OHE Pipeline

In [38]:
ohe_cols = x.select_dtypes(include='object').columns.drop(['traffic_level', 'weather'])
ohe_cols

Index(['day_of_week', 'city', 'delivery_area', 'restaurant_type',
       'restaurant_primary_category'],
      dtype='object')

In [39]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop= 'first', sparse_output= False)

ohe_pipeline = Pipeline(steps= [('OHE', ohe)])
ohe_pipeline

Pipeline(steps=[('OHE', OneHotEncoder(drop='first', sparse_output=False))])

### Assign each column to its corresponding Pipeline

In [40]:
from sklearn.compose import ColumnTransformer

preprocessing = ColumnTransformer(transformers= [
                                                ('Num Pipeline', num_pipeline, num_cols),
                                                ('BE Pipeline', BE_pipeline, BE_cols),
                                                ('Ordinal Pipeline', ord_pipeline, ord_cols),
                                                ('OHE Pipeline', ohe_pipeline, ohe_cols)
])
preprocessing

ColumnTransformer(transformers=[('Num Pipeline',
                                 Pipeline(steps=[('Median Impute',
                                                  SimpleImputer(strategy='median')),
                                                 ('Scaling', RobustScaler())]),
                                 Index(['order_hour', 'is_weekend', 'restaurant_rating', 'items_count',
       'distance_km', 'delivery_partner_experience_months',
       'delivery_partner_rating', 'restaurant_preparation_time_minutes',
       'estimated_delivery_time_m...
                                 Pipeline(steps=[('Ordinal Encoder',
                                                  OrdinalEncoder(categories=[['Low',
                                                                              'Medium',
                                                                              'High'],
                                                                             ['Clear',
                                                                              'Cloudy',
                                                                              'Rain',
                                                                              'Storm']]))]),
                                 ['traffic_level', 'weather']),
                                ('OHE Pipeline',
                                 Pipeline(steps=[('OHE',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False))]),
                                 Index(['day_of_week', 'city', 'delivery_area', 'restaurant_type',
       'restaurant_primary_category'],
      dtype='object'))])

### Test adding a model to the pipeline

In [41]:
from sklearn.linear_model import LinearRegression
model_pipeline = Pipeline(steps= [('Preprocessing', preprocessing),
                                  ('Model', LinearRegression())])
model_pipeline

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Median '
                                                                   'Impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('Scaling',
                                                                   RobustScaler())]),
                                                  Index(['order_hour', 'is_weekend', 'restaurant_rating', 'items_count',
       'distance_km', 'delivery_partner_experience_months',
       'delivery_partner_rating', 'restaurant_preparation_time_...
                                                                   OrdinalEncoder(categories=[['Low',
                                                                                               'Medium',
                                                                                               'High'],
                                                                                              ['Clear',
                                                                                               'Cloudy',
                                                                                               'Rain',
                                                                                               'Storm']]))]),
                                                  ['traffic_level', 'weather']),
                                                 ('OHE Pipeline',
                                                  Pipeline(steps=[('OHE',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse_output=False))]),
                                                  Index(['day_of_week', 'city', 'delivery_area', 'restaurant_type',
       'restaurant_primary_category'],
      dtype='object'))])),
                ('Model', LinearRegression())])

### Select Best Model

In [42]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso 
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.tree import DecisionTreeRegressor 
from sklearn.ensemble import RandomForestRegressor 
from xgboost import XGBRegressor 
from sklearn.model_selection import cross_validate 
 
models = [ 
    ('Linear Regression', LinearRegression()), 
    ('Ridge', Ridge(random_state=42)), 
    ('Lasso', Lasso(random_state=42)), 
    ('KNN', KNeighborsRegressor()), 
    ('Decision Tree', DecisionTreeRegressor(random_state=42)), 
    ('Random Forest', RandomForestRegressor(
        n_estimators=200,
        max_depth=20,
        random_state=42
    )), 
    ('XGBoost', XGBRegressor(
        n_estimators=200,
        max_depth=5,
        random_state=42
    )) 
] 
 
for model in models: 
 
    model_pipeline = Pipeline(steps=[
        ('Preprocessing', preprocessing), 
        ('Model', model[1])
    ]) 
 
    cv_result = cross_validate(
        estimator=model_pipeline, 
        X=x, 
        y=y, 
        scoring=['r2', 'neg_mean_absolute_error'], 
        cv=5, 
        return_train_score=True 
    ) 
 
    print(model[0]) 
    print('Train R2 :', cv_result['train_r2'].mean().round(4)) 
    print('Test R2 :', cv_result['test_r2'].mean().round(4)) 
    print('Test MAE :', -cv_result['test_neg_mean_absolute_error'].mean().round(4)) 
    print('\n')

Linear Regression
Train R2 : 0.9461
Test R2 : 0.9458
Test MAE : 2.5588


Ridge
Train R2 : 0.9461
Test R2 : 0.9458
Test MAE : 2.5587


Lasso
Train R2 : 0.8987
Test R2 : 0.8987
Test MAE : 3.4927


KNN
Train R2 : 0.902
Test R2 : 0.8536
Test MAE : 4.3748


Decision Tree
Train R2 : 1.0
Test R2 : 0.9129
Test MAE : 3.3746


Random Forest
Train R2 : 0.9934
Test R2 : 0.9568
Test MAE : 2.3863


XGBoost
Train R2 : 0.9758
Test R2 : 0.9663
Test MAE : 2.1449

### Best Model

In [43]:
final_pipeline = Pipeline(steps= [('Preprocessing', preprocessing),
                                      ('Model',XGBRegressor(
        n_estimators=200,
        max_depth=5,
        random_state=42
    )    ) ] )
final_pipeline

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Median '
                                                                   'Impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('Scaling',
                                                                   RobustScaler())]),
                                                  Index(['order_hour', 'is_weekend', 'restaurant_rating', 'items_count',
       'distance_km', 'delivery_partner_experience_months',
       'delivery_partner_rating', 'restaurant_preparation_time_...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=5, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=200, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [44]:
final_pipeline.fit(x, y)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Median '
                                                                   'Impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('Scaling',
                                                                   RobustScaler())]),
                                                  Index(['order_hour', 'is_weekend', 'restaurant_rating', 'items_count',
       'distance_km', 'delivery_partner_experience_months',
       'delivery_partner_rating', 'restaurant_preparation_time_...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=5, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=200, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [45]:
x.head(1)

,order_hour,day_of_week,is_weekend,city,delivery_area,restaurant_type,restaurant_primary_category,restaurant_rating,items_count,distance_km,weather,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes
0,15,Sunday,1,City_C,City_C_Area_3,Casual Dining,Healthy,4.4,4,1.1,Rain,Medium,14,4.4,25,25

In [46]:
print(x.columns.tolist())

['order_hour', 'day_of_week', 'is_weekend', 'city', 'delivery_area', 'restaurant_type', 'restaurant_primary_category', 'restaurant_rating', 'items_count', 'distance_km', 'weather', 'traffic_level', 'delivery_partner_experience_months', 'delivery_partner_rating', 'restaurant_preparation_time_minutes', 'estimated_delivery_time_minutes']

In [47]:
final_pipeline.predict(x.head(1))[0]

np.float32(30.333538)

In [48]:
final_pipeline.predict(x.sample(1))

array([29.268969], dtype=float32)

In [49]:
import joblib

# Save the full pipeline (Preprocessing + Best Model) as one file
joblib.dump(final_pipeline, 'delivery_time_model.pkl')

print("Model saved successfully ✅")

Model saved successfully ✅